---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: 2-column
- type: color
  config:
    color_format: Hex
  default: "#FF0000"
- type: include
  template: 2-column-media-element
